[theme]
primaryColor = "#3b82f6"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#121217"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
